std_msgs/Header header

geometry_msgs/Pose  r_wrist
geometry_msgs/Pose  r_elbow
geometry_msgs/Pose  r_shoulder  
geometry_msgs/Pose  l_shoulder
geometry_msgs/Pose  l_forearm
geometry_msgs/Pose  l_wrist
geometry_msgs/Pose  head
geometry_msgs/Pose  torso
geometry_msgs/Pose  waist
geometry_msgs/Pose  r_hip
geometry_msgs/Pose  r_knee
geometry_msgs/Pose  e_ankle
geometry_msgs/Pose  l_hip
geometry_msgs/Pose  l_knee
geometry_msgs/Pose  l_ankle
