string 	    device_serial_number
string	    measuring_unit 
uint16		sampling_frequency_hz
float32	    resolution 				# Resolution of the output in the indicated unit
float32 	accuracy 			    # Accuracy of the output signal tested by the manufacturer from 0-1 [%]
float32 	max_range 				# Maximal detectable input in the indicated unit
float32 	min_range 				# Minimal detectable input in the indicated unit
