DeviceInfo   device_info

string[]    electrode_placement                     # Location where the electrodes are placed 
float32     gazefield_background_light_brightness   # The brightness of the gazeflied background light in [cd/m²]
string[]    length_light_dark_phase                 # Duration of the light phase followed by the dureation of the dark phase 
string      type_lightsource                        # Which source of adapting light is used for the measurement (E.g. tungsten, halogen, ect.)
