DeviceInfo   device_info

string[]    location_lead           # Location of the lead measuring eda ("single location" or could also be multiple locations)      
string      measuring_technique     # Electrical excitation. (E.g. endosomatic methodology (ESM); exosomatic methodology (EXM))
string      current_form            # AV or DC                                                             
float32[]   scr                     # Skin conductance response -> activation of sudomotor nerve 
float32[]   scl                     # Skin conductance level -> baseline of the skin conductance 
