DeviceInfo   device_info

uint16          number_of_sensors   # Number of sensors used for the measurement
string[]        sensor_location     # Location of the sensors used to measure bcg
string          sensing_direction   # Defining along which axis bcg is measured. (E.g. dorso-ventral bcg/longitudinal BCG)
string          sensing_modality    # E.g piezoelectric-films/forceplates/ect.
string          measurement_system  # Types of system used to measure bcg. (E.g. Starr BCG/Nickerson BCG/Dock BCG/ ect.)
