DeviceInfo   device_info

uint8   channel_number 			        # The channel number of the electrode 
string  electrode_name                  # Electrode name according to the standard electrode position nomenclature 
string	electrode_placement_methode     # The standard according to which the electrodes are placed(e.g.20/10,10/10,10/5)
uint8   signal_gain                     # Gain refers to the amount by which the signals amplitude is increased or decreased[db] (Gain = 1 -> signal unchanged, gain <1 signal is attenuated, gain >1 signal is amplified)
