name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: SCAI-Lab/scai-ci-templates/.github/workflows/build_arm64.yml@main
    with:
      run_target: "pull_request"
